### PR TITLE
Lowered number from 5 to 3

### PR DESCRIPTION
**Pull request by ZELFs**
yeah... I think 5 was a lot, 3 is a bit more feasible :)

### CODE REVIEW

**Comment by staltz** [comment]
I vote `y` on this.

**Comment by arj03** [comment]
Number seems rather arbitrary. But yeah agree that 3 might be a better number.

**Comment by cblgh** [comment]
`w`

**Comment by Powersource** [comment]
y

**Comment by cblgh** [comment]
this passed with 6 votes (3 `w`) from 6 present people

**Pull request merged**
