### PR TITLE
Financial Stake - reformed

### PR DESCRIPTION
**Pull request by ZELFs**
reformed with specification

### CODE REVIEW

**Comment by arj03** [comment]
Yes! +1

**Comment by cblgh** [comment]
+1

**Comment by staltz** [comment]
I liked it how it was before, clear enough. This change makes it quite confusing, specially the first sentence.

**Comment by staltz** [comment]
How about:

"An optional recurrent contribution from each member, with the goal of covering costs for meetups. We suggest a default contribution amount."

**Comment by Powersource** [comment]
Yeah I agree with André, quite a mouthful and a bit confusing. I'd suggest we use his phrasing instead. But maybe with what we will use the money for unspecified (don't we maybe want to use it for e.g. paying grant application writers?)

**Comment by staltz** [comment]
Updated!

**Comment by cblgh** [comment]
this passed with 6 votes (2 `w`) out of 6 people present

**Pull request merged**
