### PR TITLE
Replace consortium mentions with collective

### PR DESCRIPTION
**Pull request by cblgh**
I was reading through the reasoning document and noticed that I had neglected to replace the majority of the mentions of "consortium" with "collective". This PR fixes that issue.

**Additionally**: we should probably have another vote on the name to clarify if it is the **European Scuttlebutt Collective** (what keks thought we were voting on, and what i agree with after having had the issue raised) or if it's the **European SSB Collective** (which was what arj wrote in [his proposal](https://github.com/scuttlebutt-eu/important-documents/pull/33#issuecomment-664030988))

### CODE REVIEW

**Comment by staltz** [comment]
## `y`

**Comment by cblgh** [comment]
thx andre

**Comment by elavoie** [comment]
I think we do not need to vote on this PR, because it is coherent with previous decisions and does not change the meaning of the document.

Feel free to directly merge in master.

**Comment by cblgh** [comment]
merged per https://github.com/scuttlebutt-eu/important-documents/pull/42#issuecomment-679061220

**Pull request merged**
