### PR TITLE
Conflict resolution keks (Request-For-Comments)

### LINKED ISSUE #29: Add conflict resolution outline
Rather than establishing a process to vote a member out of the consortium, provide high-level guidelines for conflict resolution/de-escalation.

### PR DESCRIPTION
**Pull request by keks**
Fixes https://github.com/scuttlebutt-eu/important-documents/issues/29

This is an alternative proposal to https://github.com/scuttlebutt-eu/important-documents/pull/31. That PR had some unaddressed comments, which I hope to resolve with this PR.

### CODE REVIEW

**Comment by Powersource** [comment]
If anyone wants to read the specific diff compared to Erick's proposal: https://github.com/scuttlebutt-eu/important-documents/pull/38/commits/5fbb8823d76e38c97e04d172b6348d5d08ac14de

**Comment by Powersource** [comment]
y

**Comment by elavoie** [comment]
@keks @Powersource 
That is good good for me, we can merge it.

**Comment by cblgh** [comment]
y

**Comment by staltz** [comment]
w

**Pull request merged**
