### PR TITLE
Reword pay

### LINKED ISSUE #18: Reword pay section under criteria

### PR DESCRIPTION
**Pull request by arj03**
This fixes #18. I removed the transparent section as that is not really relevant to the members section.

### CODE REVIEW

**Comment by keks** [comment]
@arj03 In another place the document says the amount is variable, which I think is correct.

**Comment by arj03** [comment]
Rewording it a bit to make that more clear. Thanks @keks

**Comment by Powersource** [comment]
y

**Comment by Powersource** [comment]
We voted in the meeting to merge this

**Pull request merged**
