### PR TITLE
Add reasoning document

### LINKED ISSUE #16: Add "guidelines" document
A doc that explains the ideas behind the membership doc and goes through some example processes

### PR DESCRIPTION
**Pull request by keks**
Fixes #16

### CODE REVIEW

**Comment by cblgh** [comment]
>  "rando" is a technical Scuttlebutt term

lol'd (in a good way)

**Comment by Powersource** [comment]
y

**Comment by elavoie** [comment]
@keks I really like this, I think you did a great job of synthesizing our past discussions.

May I add a one-paragraph summary of my "Commitment" essay (ssb: %zOzISIYGbk/FVIRH+O+sqA6ewjDmb+lkbwcfkV0eGOo=.sha256) in the Active Membership section? Do you think that could help flesh out the reasoning?

**Comment by cblgh** [comment]
@keks echoing what has been said by others, this is great. i fixed a few passages i felt were confusing, and streamlined the use of _consortium_ throughout the document, and generally made the document a bit of an easier first read. 

(let me know if i overstepped anywhere in my commit https://github.com/scuttlebutt-eu/important-documents/pull/24/commits/f16f9dab66d2d57ffb433654c0047cd4741bbc25!)

edit: having seen your PR https://github.com/scuttlebutt-eu/important-documents/pull/27, i think i now understand what you meant :~

**Comment by staltz** [comment]
y

**Pull request merged**
