### PR TITLE
[Draft] Add member removal process

### PR DESCRIPTION
**Pull request by staltz**
For issue #14. The phrasing I used is obviously up for edits and further clarification.

### CODE REVIEW

**Comment by cblgh** [comment]
@staltz nice :) perhaps we should mention the criteria for successful removal as well? i assume you intend for removal of the member to be passed if (1) everyone has voted, and (2) all of the votes are either `w` or `y`

in that vein, absentees should probably be defined somehow (does a vote fail if someone does not vote? or is that equivalent to a `w` vote?)

**Comment by staltz** [comment]
I think we need a document to describe our `yw!?` voting process, specially because it's so central to everything we do! That should address some of your questions. I do think that it's reasonable if a member doesn't answer within the deadline, to consider their vote as `w`. What is your opinion?

**Comment by cblgh** [comment]
yeah i think that's reasonable too, i think, as long as a majority (>=50%) of the consortium has _actually_ voted. just to explicitly close off any weird situations where e.g. someone poses a vote at a busy time like the new year's week or w/e

is that reasonable?

**Comment by elavoie** [comment]
Perhaps I would simply add "in exceptional situations, when all other conflict resolution strategies have failed."

**Comment by Powersource** [comment]
It feels a bit much to me to need everyone to agree/don't mind (y/w) to remove a member. What if there are 100 people in the org, 98 people want someone gone, but 1 person is blocking the removal? Is that the part where we invoke the Membership split, which is essentially a majority vote? If so, (or maybe either way) I think it could be a good idea to include in the text how the Membership split plays into this.

Also agree with Erick that we should mention a conflict resolution strategy, even if we don't define that in this document.

**Comment by Powersource** [comment]
Or is this maybe where https://github.com/scuttlebutt-eu/important-documents/issues/16 comes in?

**Comment by staltz** [comment]
I'm hoping that as we scale and go beyond 30 members, we will completely refresh our processes (I think we kind of agreed that we would do that after 1 year?), so I'm just trying to provide a starting point that we can use for removal.

**Comment by Powersource** [comment]
Ok that makes sense. I'm leaning towards preferring just using a majority vote to start with though.

Also anyway, this PR atm is more lax than the

> Be actively vouched for by at least 3 active members (see “Membership Split” for limit cases)

criteria, which kind of makes this pr superfluous in a way?

**Comment by Powersource** [comment]
Now that I've read https://github.com/scuttlebutt-eu/important-documents/pull/24 , I think this pr (#21) could probably be skipped.

**Comment by elavoie** [comment]
I would agree with @Powersource that the possibility of removing vouching at any time, as explained in #24, is a form of voting that can remove someone/some groups from the consortium. It thus supersedes the need for an explicit vote for removal.

It also provides an escalation mechanism without requiring a consensus-based process: When someone removes their vouching, this sends a signal of disagreement that the "unvouched" member can use to adapt their behaviour. This works without anyone having to do a formal "intervention" with that person, and without mobilizing the entire organization on a vote to threaten the person for removal. Yet, if anti-social behaviour is maintained, then the other members that will remove their vouching will create an escalation until actual removal.

I added a commit in #24 to add one sentence that clarifies that a vouch can be removed at any time: https://github.com/scuttlebutt-eu/important-documents/pull/24/commits/ce61d371d1ce8d45014e00333f0f525ed3b77ad6

**Pull request closed without merging**
