### PR TITLE
Actively ensure rules are current

### PR DESCRIPTION
**Pull request by arj03**
I think it is important to add this section, even if it seems a bit self-evident for the current members. In general I think its a good principle and should hopefully make it clear to members coming in after the initial group that they have as much to say about what the rules should be.

### CODE REVIEW

**Comment by Powersource** [comment]
This feels weird to put in the "Criteria" section, it's no requirement, it's more of a priviledge. Maybe we should make a new section for that kind of thing? And there we could also put some of the stuff from https://github.com/scuttlebutt-eu/important-documents/issues/2

**Comment by arj03** [comment]
As I read Criteria it is things you *must* do as a member, and I think this rule actually belongs to that class ;-)

**Comment by ZELFs** [comment]
I agree with this one, my vote is Y 

Regarding where to place it, I think that can be sorted out later as long as it's still in a segment which clarifies that it's something that is a task of all the members in the consortium / a task of the consortium. 

Later it could make sense to have it in a "Bylaws" section.

**Comment by arj03** [comment]
Closed for now

**Pull request closed without merging**
